/**
 * Services Orders API Swagger
 * These are the services for Services Orders
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.7
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Area', 'model/Supplier'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Area'), require('./Supplier'));
  } else {
    // Browser globals (root is window)
    if (!root.ServicesOrdersApiSwagger) {
      root.ServicesOrdersApiSwagger = {};
    }
    root.ServicesOrdersApiSwagger.ServiceOrder = factory(root.ServicesOrdersApiSwagger.ApiClient, root.ServicesOrdersApiSwagger.Area, root.ServicesOrdersApiSwagger.Supplier);
  }
}(this, function(ApiClient, Area, Supplier) {
  'use strict';




  /**
   * The ServiceOrder model module.
   * @module model/ServiceOrder
   * @version 1.0
   */

  /**
   * Constructs a new <code>ServiceOrder</code>.
   * @alias module:model/ServiceOrder
   * @class
   */
  var exports = function() {
    var _this = this;















  };

  /**
   * Constructs a <code>ServiceOrder</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ServiceOrder} obj Optional instance to populate.
   * @return {module:model/ServiceOrder} The populated <code>ServiceOrder</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('orderNumber')) {
        obj['orderNumber'] = ApiClient.convertToType(data['orderNumber'], 'String');
      }
      if (data.hasOwnProperty('orderDate')) {
        obj['orderDate'] = ApiClient.convertToType(data['orderDate'], 'Date');
      }
      if (data.hasOwnProperty('endDate')) {
        obj['endDate'] = ApiClient.convertToType(data['endDate'], 'Date');
      }
      if (data.hasOwnProperty('area')) {
        obj['area'] = ApiClient.convertToType(data['area'], [Area]);
      }
      if (data.hasOwnProperty('supplier')) {
        obj['supplier'] = ApiClient.convertToType(data['supplier'], [Supplier]);
      }
      if (data.hasOwnProperty('requester')) {
        obj['requester'] = ApiClient.convertToType(data['requester'], 'String');
      }
      if (data.hasOwnProperty('numberRequest')) {
        obj['numberRequest'] = ApiClient.convertToType(data['numberRequest'], 'String');
      }
      if (data.hasOwnProperty('quantity')) {
        obj['quantity'] = ApiClient.convertToType(data['quantity'], 'Number');
      }
      if (data.hasOwnProperty('priceTotal')) {
        obj['priceTotal'] = ApiClient.convertToType(data['priceTotal'], 'Number');
      }
      if (data.hasOwnProperty('paymentMethod')) {
        obj['paymentMethod'] = ApiClient.convertToType(data['paymentMethod'], 'String');
      }
      if (data.hasOwnProperty('reference')) {
        obj['reference'] = ApiClient.convertToType(data['reference'], 'String');
      }
      if (data.hasOwnProperty('status')) {
        obj['status'] = ApiClient.convertToType(data['status'], 'String');
      }
      if (data.hasOwnProperty('complete')) {
        obj['complete'] = ApiClient.convertToType(data['complete'], 'Boolean');
      }
    }
    return obj;
  }

  /**
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {String} orderNumber
   */
  exports.prototype['orderNumber'] = undefined;
  /**
   * @member {Date} orderDate
   */
  exports.prototype['orderDate'] = undefined;
  /**
   * @member {Date} endDate
   */
  exports.prototype['endDate'] = undefined;
  /**
   * @member {Array.<module:model/Area>} area
   */
  exports.prototype['area'] = undefined;
  /**
   * @member {Array.<module:model/Supplier>} supplier
   */
  exports.prototype['supplier'] = undefined;
  /**
   * @member {String} requester
   */
  exports.prototype['requester'] = undefined;
  /**
   * @member {String} numberRequest
   */
  exports.prototype['numberRequest'] = undefined;
  /**
   * @member {Number} quantity
   */
  exports.prototype['quantity'] = undefined;
  /**
   * @member {Number} priceTotal
   */
  exports.prototype['priceTotal'] = undefined;
  /**
   * @member {String} paymentMethod
   */
  exports.prototype['paymentMethod'] = undefined;
  /**
   * @member {String} reference
   */
  exports.prototype['reference'] = undefined;
  /**
   * Order Status
   * @member {module:model/ServiceOrder.StatusEnum} status
   */
  exports.prototype['status'] = undefined;
  /**
   * @member {Boolean} complete
   * @default false
   */
  exports.prototype['complete'] = false;


  /**
   * Allowed values for the <code>status</code> property.
   * @enum {String}
   * @readonly
   */
  exports.StatusEnum = {
    /**
     * value: "Draft"
     * @const
     */
    "Draft": "Draft",
    /**
     * value: "Open"
     * @const
     */
    "Open": "Open",
    /**
     * value: "Cancelled"
     * @const
     */
    "Cancelled": "Cancelled"  };


  return exports;
}));


