/**
 * Services Orders API Swagger
 * These are the services for Services Orders
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.7
 *
 * Do not edit the class manually.
 *
 */

(function(factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Area', 'model/Item', 'model/ServiceOrder', 'model/Supplier', 'api/LineItemApi', 'api/ServicesOrdersApi'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('./ApiClient'), require('./model/Area'), require('./model/Item'), require('./model/ServiceOrder'), require('./model/Supplier'), require('./api/LineItemApi'), require('./api/ServicesOrdersApi'));
  }
}(function(ApiClient, Area, Item, ServiceOrder, Supplier, LineItemApi, ServicesOrdersApi) {
  'use strict';

  /**
   * These_are_the_services_for_Services_Orders.<br>
   * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
   * <p>
   * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
   * <pre>
   * var ServicesOrdersApiSwagger = require('index'); // See note below*.
   * var xxxSvc = new ServicesOrdersApiSwagger.XxxApi(); // Allocate the API class we're going to use.
   * var yyyModel = new ServicesOrdersApiSwagger.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
   * and put the application logic within the callback function.</em>
   * </p>
   * <p>
   * A non-AMD browser application (discouraged) might do something like this:
   * <pre>
   * var xxxSvc = new ServicesOrdersApiSwagger.XxxApi(); // Allocate the API class we're going to use.
   * var yyy = new ServicesOrdersApiSwagger.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * </p>
   * @module index
   * @version 1.0
   */
  var exports = {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient: ApiClient,
    /**
     * The Area model constructor.
     * @property {module:model/Area}
     */
    Area: Area,
    /**
     * The Item model constructor.
     * @property {module:model/Item}
     */
    Item: Item,
    /**
     * The ServiceOrder model constructor.
     * @property {module:model/ServiceOrder}
     */
    ServiceOrder: ServiceOrder,
    /**
     * The Supplier model constructor.
     * @property {module:model/Supplier}
     */
    Supplier: Supplier,
    /**
     * The LineItemApi service constructor.
     * @property {module:api/LineItemApi}
     */
    LineItemApi: LineItemApi,
    /**
     * The ServicesOrdersApi service constructor.
     * @property {module:api/ServicesOrdersApi}
     */
    ServicesOrdersApi: ServicesOrdersApi
  };

  return exports;
}));
