/**
 * Services Orders API Swagger
 * These are the services for Services Orders
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.7
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ServicesOrdersApiSwagger);
  }
}(this, function(expect, ServicesOrdersApiSwagger) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ServicesOrdersApiSwagger.ServicesOrdersApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ServicesOrdersApi', function() {
    describe('deleteServiceOrder', function() {
      it('should call deleteServiceOrder successfully', function(done) {
        //uncomment below and update the code to test deleteServiceOrder
        //instance.deleteServiceOrder(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAllServiceOrders', function() {
      it('should call getAllServiceOrders successfully', function(done) {
        //uncomment below and update the code to test getAllServiceOrders
        //instance.getAllServiceOrders(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getOrderById', function() {
      it('should call getOrderById successfully', function(done) {
        //uncomment below and update the code to test getOrderById
        //instance.getOrderById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('placeServiceOrder', function() {
      it('should call placeServiceOrder successfully', function(done) {
        //uncomment below and update the code to test placeServiceOrder
        //instance.placeServiceOrder(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateServiceOrder', function() {
      it('should call updateServiceOrder successfully', function(done) {
        //uncomment below and update the code to test updateServiceOrder
        //instance.updateServiceOrder(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
