/**
 * Services Orders API Swagger
 * These are the services for Services Orders
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.7
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ServicesOrdersApiSwagger);
  }
}(this, function(expect, ServicesOrdersApiSwagger) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ServicesOrdersApiSwagger.Supplier();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Supplier', function() {
    it('should create an instance of Supplier', function() {
      // uncomment below and update the code to test Supplier
      //var instance = new ServicesOrdersApiSwagger.Supplier();
      //expect(instance).to.be.a(ServicesOrdersApiSwagger.Supplier);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new ServicesOrdersApiSwagger.Supplier();
      //expect(instance).to.be();
    });

    it('should have the property code (base name: "code")', function() {
      // uncomment below and update the code to test the property code
      //var instance = new ServicesOrdersApiSwagger.Supplier();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instance = new ServicesOrdersApiSwagger.Supplier();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new ServicesOrdersApiSwagger.Supplier();
      //expect(instance).to.be();
    });

    it('should have the property telephoneNumber (base name: "telephoneNumber")', function() {
      // uncomment below and update the code to test the property telephoneNumber
      //var instance = new ServicesOrdersApiSwagger.Supplier();
      //expect(instance).to.be();
    });

    it('should have the property address (base name: "address")', function() {
      // uncomment below and update the code to test the property address
      //var instance = new ServicesOrdersApiSwagger.Supplier();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instance = new ServicesOrdersApiSwagger.Supplier();
      //expect(instance).to.be();
    });

  });

}));
